# Generated by Django 4.0.3 on 2022-04-15 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_author_alter_newsmodel_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('primer', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date')),
            ],
        ),
    ]
