# Generated by Django 4.0.3 on 2022-04-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articlmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlModel',
            new_name='ArticleModel',
        ),
    ]
